/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c FileHelper -a filehelper_adaptor FileOperationsInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef FILEHELPER_ADAPTOR_H
#define FILEHELPER_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.example.filehelper
 */
class FileHelper: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.example.filehelper")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.example.filehelper\">\n"
"    <method name=\"DeleteFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"filePath\"/>\n"
"    </method>\n"
"    <method name=\"PasteFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"source\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"destination\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    FileHelper(QObject *parent);
    virtual ~FileHelper();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void DeleteFile(const QString &filePath);
    void PasteFile(const QString &source, const QString &destination);
Q_SIGNALS: // SIGNALS
};

#endif
